services:
  # --- INGESTION WORKER (Standalone) ---
  rioja_ingest:
    build: .
    image: rioja-airflow-custom:v1
    container_name: rioja_ingest_container
    profiles: ["manual"] 
    volumes:
      - .:/app
      - /app/.venv
      - ./keys:/app/keys
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/credentials.json
    stdin_open: true
    tty: true

  # --- METADATA DATABASE ---
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- AIRFLOW WEBSERVER ---
  airflow-webserver:
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    image: rioja-airflow-custom:v1
    depends_on:
      postgres: { condition: service_healthy }
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./keys:/opt/airflow/keys
      - .:/opt/airflow/rioja_logic 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/keys/credentials.json
    command: webserver

  # --- AIRFLOW SCHEDULER ---
  airflow-scheduler:
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    image: rioja-airflow-custom:v1
    depends_on:
      postgres: { condition: service_healthy }
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./keys:/opt/airflow/keys
      - .:/opt/airflow/rioja_logic
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/keys/credentials.json
    command: scheduler

  # --- AIRFLOW INIT ---
  airflow-init:
    build: 
      context: .
      dockerfile: Dockerfile.airflow
    image: rioja-airflow-custom:v1
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --password admin --firstname Rioja --lastname Admin --role Admin --email admin@example.com"