rioja_transform:
  outputs:
    dev:
      dataset: rioja_wine_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/gcp/rioja-wine-pipeline/keys/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: project-1314e5d0-dc4a-4a2f-804
      threads: 4
      type: bigquery
  target: dev
